### ISSUE TITLE
ReportBuilder fails with UnsupportedOperationException: empty.max

### ISSUE THREAD

**Issue by iantmoore** [Substeps/substeps-framework#38]
java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:227)
	at scala.collection.AbstractTraversable.max(Traversable.scala:104)
	at org.substeps.report.ReportBuilder.getJSTreeCallHierarchyForStepImpls(ReportBuilder.scala:433)

possibly caused by a test suite not running any tests and falling over when creating the report.

**Comment by iantmoore** [comment]
fixed
