### ISSUE TITLE
Issue running substeps framework on jenkins - no substeps file or directory specified

### ISSUE THREAD

**Issue by aneeshchakko** [Substeps/substeps-framework#80]
I get the following issue running the substeps framework on jenkins. Please advise

[ERROR] Failed to execute goal org.substeps:substeps-maven-plugin:1.1.1:run-features (default-cli) on project webdriver-substeps-example: Substeps configuration problem: no substeps file or directory specified -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by iantmoore** [comment]
Hi aneeshchakko,

As the error states, the substeps runner can't locate the directory containing the .substeps files - but we need to understand why -  If you can run the maven job with -X it should produce more logging which, including the merged and resolved config that is being run and in which there should be a substeps directory.  If you can't see anything obvious, can you paste the output from running with -X and I'll take a look.

**Comment by aneeshchakko** [comment]
Hi iantmoore, thanks for the quick response! I am running this on Jenkins, it runs fine on my ide IntelliJ. I can't seem to understand why it still fails from below. 

[ERROR] Failed to execute goal org.substeps:substeps-maven-plugin:1.1.1:run-features (default-cli) on project webdriver-substeps-example: Substeps configuration problem: no substeps file or directory specified -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.substeps:substeps-maven-plugin:1.1.1:run-features (default-cli) on project webdriver-substeps-example: Substeps configuration problem
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoExecutionException: Substeps configuration problem
	at com.technophobia.substeps.runner.BaseSubstepsMojo.executeNewConfigs(BaseSubstepsMojo.java:239)
	at com.technophobia.substeps.runner.BaseSubstepsMojo.execute(BaseSubstepsMojo.java:220)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
Caused by: com.technophobia.substeps.model.exception.SubstepsConfigurationException: no substeps file or directory specified
	at org.substeps.runner.NewSubstepsExecutionConfig$.getStringOrThrow(NewSubstepsExecutionConfig.scala:137)
	at org.substeps.runner.NewSubstepsExecutionConfig$.validateExecutionConfig(NewSubstepsExecutionConfig.scala:119)
	at org.substeps.runner.NewSubstepsExecutionConfig.validateExecutionConfig(NewSubstepsExecutionConfig.scala)
	at com.technophobia.substeps.runner.BaseSubstepsMojo.executeNewConfigs(BaseSubstepsMojo.java:235)
	... 34 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[JENKINS] Archiving /var/jenkins/workspace/Staging/Test for Aneesh/pom.xml to org.substeps/webdriver-substeps-example/1.4.1/webdriver-substeps-example-1.4.1.pom
channel stopped
[PostBuildScript] - Executing post build scripts.
[Test for Aneesh] $ /bin/sh -xe /tmp/jenkins1611903597096325132.sh
Finished: FAILURE

**Comment by iantmoore** [comment]
firstly can I check the maven goal you are using ?  Can you change the jenkins job configuration to add a -X as a parameter to the mvn command - that should create more debug output

**Comment by aneeshchakko** [comment]
the previous message is running it with -X

**Comment by iantmoore** [comment]
ok, I'm not sure the -X parameter is making it's way through to maven for some reason because I'd expect more output and also there's this:
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`

Anyway, I think the issue might be this:
in application.conf the path to the substeps files is something like this:
`substepsFile=${project.build.testOutputDirectory}"/substeps"`
 
project.build.testOutputDirectory will be replaced with <project>/target/test-classes/substeps.
but if you run the substeps goal directly rather than verify for example, maven won't run the proceeding goals, compile etc that would copy resources over etc.  Does that directory exist ?

**Comment by aneeshchakko** [comment]
I tried just mvn verify -X and I get the following error log. It is weird how it still asks to re-run with -X. If I download your example project and do a mvn verify on a jenkins job, should it still work?

[INFO] Loading environment config file: localhost.conf
[DEBUG] Env config:
{}

[DEBUG] resolveConfig
[DEBUG] masterConfig:
org {
    substeps {
        baseExecutionConfig {
            executionListeners=[
                "com.technophobia.substeps.runner.logger.StepExecutionLogger"
            ]
            fastFailParseErrors=true
            featureFile=${project.build.testOutputDirectory}"/features"
            initialisationClasses=[
                "com.technophobia.webdriver.substeps.example.ExampleSetupAndTearDown"
            ]
            stepImplementationClassNames=[
                "com.technophobia.webdriver.substeps.impl.BaseWebdriverSubStepImplementations",
                "com.technophobia.webdriver.substeps.example.ExampleCustomWebdriverStepImplementations"
            ]
            substepsFile=${project.build.testOutputDirectory}"/substeps"
            tags="@all"
            webdriver {
                driver {
                    type=HTMLUNIT
                }
            }
        }
        config {
            checkForUncalledAndUnused=false
            current {
                branchname=d0adab7181e5dc9585d951347b5242824185b50a
                projectversion="1.4.1"
            }
            description="Self Test Features"
            executionResultsCollector="org.substeps.report.ExecutionResultsCollector"
            jmxPort=9999
            log {
                unused {
                    uncalled=false
                }
            }
            parameter {
                substitution {
                    enabled=true
                    end="}"
                    normalize {
                        from=ISO-8859-1
                        to=UTF-8
                    }
                    normalizeValue=false
                    start="${"
                }
            }
            report {
                data {
                    pretty {
                        print=false
                    }
                }
                rootNodeDescriptionProvider="org.substeps.report.DefaultDescriptionProvider"
            }
            reportBuilder="org.substeps.report.ReportBuilder"
            reportDir="target/substeps_report"
            rootDataDir="target/substeps_data"
            runTestsInForkedVM=true
            step {
                depth {
                    description=6
                }
            }
        }
        executionConfigs=[
            {
                dataOutputDir=""
                description="Self Test Features"
                webdriver {
                    driver {
                        type=CHROME
                    }
                }
            }
        ]
        webdriver {
            base {
                url="http://substeps.github.io/substeps-webdriver/"
            }
            default {
                timeout {
                    secs=5
                }
            }
            htmlunit {
                disable {
                    javascript=false
                }
            }
            locale=en-gb
            log {
                pagesource {
                    onerror=false
                }
            }
            network {
                proxy {
                    host=""
                    port=8080
                }
            }
            reuse-strategy="shutdown_and_create_new"
            wait {
                seconds=25
            }
            webdriver {
                manager {
                    properties=""
                }
            }
            window {
                maximise=true
            }
        }
    }
}

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.252 s
[INFO] Finished at: 2018-03-15T00:22:25+00:00
[INFO] Final Memory: 23M/242M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.substeps:substeps-maven-plugin:1.1.1:generate-docs (Build SubSteps Glossary) on project webdriver-substeps-example: Execution Build SubSteps Glossary of goal org.substeps:substeps-maven-plugin:1.1.1:generate-docs failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.substeps:substeps-maven-plugin:1.1.1:generate-docs (Build SubSteps Glossary) on project webdriver-substeps-example: Execution Build SubSteps Glossary of goal org.substeps:substeps-maven-plugin:1.1.1:generate-docs failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution Build SubSteps Glossary of goal org.substeps:substeps-maven-plugin:1.1.1:generate-docs failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
Caused by: java.lang.NullPointerException
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at com.technophobia.substeps.glossary.SubstepsGlossaryMojo.executeAfterAllConfigs(SubstepsGlossaryMojo.java:186)
	at com.technophobia.substeps.runner.BaseSubstepsMojo.execute(BaseSubstepsMojo.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 32 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[JENKINS] Archiving /var/jenkins/workspace/Staging/Test for Aneesh/pom.xml to org.substeps/webdriver-substeps-example/1.4.1/webdriver-substeps-example-1.4.1.pom
channel stopped
[PostBuildScript] - Executing post build scripts.
[Test for Aneesh] $ /bin/sh -xe /tmp/jenkins5402939243613983355.sh
Finished: FAILURE

**Comment by aneeshchakko** [comment]
Also /target/test-classes/substeps does not exist for me. Why would it do look here?

My conf and substeps files are in src/test/resources

**Comment by aneeshchakko** [comment]
Is it possible we can have a quick call or chat tomorrow at your convenience to talk about this further? I would like to implement this framework for my Company.

**Comment by iantmoore** [comment]
Sorry, I don't think a call will be possible, but I'm happy to help out here.
using mvn verify, I think you've exposed a problem:
generate-docs failed. NullPointerException 
I'll take a look at that tonight, it could be that the example needs updating with the latest libraries.
A quick work around is to **remove** the GlossaryBuilding from the pom.
line 201-207 in the example:
<execution>
  <id>Build SubSteps Glossary</id>
  <phase>process-test-resources</phase>
  <goals>
    <goal>generate-docs</goal>
  </goals>
</execution>

see what happens then and I'll take a look properly tonight.

However, if  <project directory> /target/test-classes/substeps  doesn't exist, then it suggests that the code isn't compiling and it's not going to find any compiled step implementations...

You can configure substeps to look for your substeps and feature files anywhere - just override the defaults. see http://substeps.github.io/indepth/configuration/ for more details on the configuration.  

Can I also ask, is Jenkins running locally ?  Could you let me know the version of maven and jenkins you're using ?  Also, you might find it easier to remove jenkins from the equation initially and run maven from the command line.  Also what OS is this running on ?

**Comment by iantmoore** [comment]
I've just updated the example project to include the latest versions of the substeps libraries.  I'd suggets trying that to resolve the null pointer issue above.

**Comment by aneeshchakko** [comment]
Yes, the example works on jenkins! I will have to try my own features, but I think we are good to close this Issue.

**Comment by iantmoore** [comment]
great, glad to hear it!
